// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QLHV_API.proc
{
    public partial class GetDiemResult
    {
        public Guid id_HV { get; set; }
        [Column("chuyencan", TypeName = "decimal(3,1)")]
        public decimal? chuyencan { get; set; }
        [Column("thuongxuyen", TypeName = "decimal(3,1)")]
        public decimal? thuongxuyen { get; set; }
        [Column("hocky", TypeName = "decimal(3,1)")]
        public decimal? hocky { get; set; }
        [Column("tongket", TypeName = "decimal(3,1)")]
        public decimal? tongket { get; set; }
        public Guid? creator { get; set; }
        public Guid? editor { get; set; }
        public DateTime? create_time { get; set; }
        public DateTime? edit_time { get; set; }
        public int id_LMH { get; set; }
    }
}
