// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QLHV_API.proc
{
    public partial class GetNguoiDungByIdResult
    {
        public Guid id { get; set; }
        public string ten { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public Guid donvi { get; set; }
        public bool? gioitinh { get; set; }
        public DateTime? ngaysinh { get; set; }
        public string hinhanh { get; set; }
        public string quequan { get; set; }
        public string trangthai { get; set; }
        public string id_quyen { get; set; }
        public Guid? creator { get; set; }
        public Guid? editor { get; set; }
        public DateTime? create_time { get; set; }
        public string email { get; set; }
        public string cccd { get; set; }
        public DateTime? edit_time { get; set; }
    }
}
