// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QLHV_API.proc
{
    public partial class GetTrangThaiHVResult
    {
        public string ma { get; set; }
        public string ten { get; set; }
        public string mota { get; set; }
    }
}
