// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using QLHV_API.proc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace QLHV_API.proc
{
    public partial interface IQLHVContextProcedures
    {
        Task<int> AddHocVienAsync(string hoten, string sdt, string diachi, string quequan, DateTime? ngaysinh, bool? gioitinh, string loai, Guid? lop, string note, Guid? creator, string cccd, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteDonViAsync(Guid? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> deleteHVAsync(Guid? id, Guid? editor, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteNguoiDungAsync(Guid? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> deleteTrangThaiHVAsync(string ma, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetDetailHVResult>> GetDetailHVAsync(Guid? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetDiemResult>> GetDiemAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetHVResult>> GetHVAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetJsonStringDataResult>> GetJsonStringDataAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetNguoiDungResult>> GetNguoiDungAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetNguoiDungByIdResult>> GetNguoiDungByIdAsync(Guid? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetOrganizationHierarchyResult>> GetOrganizationHierarchyAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetTrangThaiHVResult>> GetTrangThaiHVAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetTrangThaiHVByIdResult>> GetTrangThaiHVByIdAsync(string ma, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertDonViAsync(string ten, string sdt, string diachi, Guid? chihuy, string madv, Guid? thuoc, string trangthai, string loai, Guid? creator, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> insertLopMonHocAsync(Guid? lop, int? monhoc, Guid? creator, Guid? giangvien, int? hk, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> InsertNguoiDungAsync(string ten, string sdt, string diachi, Guid? donvi, bool? gioitinh, DateTime? ngaysinh, string quequan, string trangthai, string id_quyen, Guid? creator, string email, string cccd, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<searchHVResult>> searchHVAsync(string search, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<searchNguoiDungResult>> searchNguoiDungAsync(string tuKhoa, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> updateDonViAsync(Guid? id, string ten, string sdt, string diachi, Guid? chihuy, string madv, Guid? thuoc, string trangthai, string loai, Guid? creator, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> updateHocVienAsync(Guid? id, string hoten, string sdt, string diachi, string quequan, DateTime? ngaysinh, bool? gioitinh, string trangthai, string loai, Guid? lop, string note, Guid? editor, string cccd, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateNguoiDungAsync(Guid? id, string ten, string sdt, string diachi, Guid? donvi, bool? gioitinh, DateTime? ngaysinh, string quequan, string trangthai, string id_quyen, Guid? editor, string email, string cccd, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_InsertDONVIAsync(string ten, int? quanso, string sdt, Guid? chihuy, string loai, string diachi, Guid? thuoc, Guid? creator, string maDV, string trangthai, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_UpdateDONVIAsync(Guid? id, string ten, int? quanso, string sdt, Guid? chihuy, string loai, string diachi, Guid? thuoc, Guid? editor, string maDV, string trangthai, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
