// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using QLHV_API.proc;

namespace QLHV_API.proc
{
    public partial class QLHVContext
    {

        [DbFunction("ComputeSha256Hash", "dbo")]
        public static string ComputeSha256Hash(string rawData)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("ConvertTableToJson", "dbo")]
        public static string ConvertTableToJson()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GenerateLop", "dbo")]
        public static string GenerateLop(Guid? lop)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GenerateMaHV", "dbo")]
        public static string GenerateMaHV()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetDay", "dbo")]
        public static string GetDay(DateTime? Date)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("getDV", "dbo")]
        public static string getDV()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("getDVbyid", "dbo")]
        public static string getDVbyid(Guid? id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetEmployeesAsJson", "dbo")]
        public static string GetEmployeesAsJson()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetProductByIdAsJson", "dbo")]
        public static string GetProductByIdAsJson(Guid? id)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("thuocquyen", "dbo")]
        public IQueryable<thuocquyenResult> thuocquyen(Guid? ID)
        {
            return FromExpression(() => thuocquyen(ID));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<thuocquyenResult>().HasNoKey();
        }
    }
}
