// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QLHV_API.proc
{
    public partial class searchHVResult
    {
        public Guid id { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public string quequan { get; set; }
        public DateTime? ngaysinh { get; set; }
        public bool? gioitinh { get; set; }
        public string hinhanh { get; set; }
        public string trangthai { get; set; }
        public string loai { get; set; }
        public Guid? lop { get; set; }
        public string note { get; set; }
        public Guid? creator { get; set; }
        public Guid? editor { get; set; }
        public DateTime? create_time { get; set; }
        public string doituong { get; set; }
        public string MaHV { get; set; }
        public DateTime? edit_time { get; set; }
        public string hoten { get; set; }
        public string tenlop { get; set; }
        public string cccd { get; set; }
    }
}
